# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Edgar Magdaleno
email: edgarmv97@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Student - Game Developer
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://edgarmagdaleno.github.io" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
github_username:  EdgarMagdaleno

# Build settings
markdown: kramdown
